export const CREATE_NEW_USER = 'CREATE_NEW_USER';

//cart
export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const REMOVE_ITEM_ARROWS = 'REMOVE_ITEM_ARROWS';
export const CLEAR_CART_CHECKOUT = 'CLEAR_CART_CHECKOUT';